package:
  name: molearn

source:
  path: ../

build:
  number: 0

sphinx:
  configuration: source/conf.py
  
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pytorch
    - pandas
    - scipy
test:
  imports:
    - molearn

