{% set version = "1.1.0" %}

package:
  name: molearn
  version: {{ version }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pytorch
    - pandas
    - scipy
test:
  imports:
    - molearn

