name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda + mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          activate-environment: base
          mamba-version: '*'
          channels: conda-forge,defaults
          channel-priority: strict
          auto-update-conda: false
          remove-profiles: true
          conda-solver: libmamba
          clean-patched-environment-file: true
          environment-file: environment.yml
          run-post: true

      - name: Test
        run: |
          cd test
          python test_openmm_plugin.py
          python test_pdbdata.py
          python test_trainer.py
