name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Add conda to PATH
      run: |
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install mamba
      run: |
        # install mamba into the base conda env
        conda install -n base -c conda-forge mamba -y

    - name: Install dependencies with mamba
      run: |
        # this will be much faster than conda's solver
        mamba env update --file environment.yml --name base

    - name: Test
      run: |
        cd test
        python test_openmm_plugin.py
        python test_pdbdata.py
        python test_trainer.py
