name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        # ensure shells load conda correctly for activation
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda + mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          # install Python 3.11
          python-version: '3.11'
          # tell it to pull in mamba from conda-forge
          mamba-version: '*'
          # solve using conda-forge (mamba is fastest here)
          channels: conda-forge,defaults
          channel-priority: strict
          # update the base env instead of creating `test`
          auto-activate-base: true
          activate-environment: ""
          environment-file: environment.yml

      - name: Test
        run: |
          cd test
          python test_openmm_plugin.py
          python test_pdbdata.py
          python test_trainer.py
