name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda + mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: molearn
          environment-file: .github/test_environment.yml
          mamba-version: '*'
          conda-solver: libmamba
          channels: pytorch,nvidia,conda-forge,salilab,plotly,defaults
          channel-priority: strict
          auto-update-conda: false
          remove-profiles: true
          run-post: true
      - name: Test
        run: |
          cd test
          python test_openmm_plugin.py
          python test_pdbdata.py
          python test_trainer.py
