name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      # point Conda/mamba at a temp directory for package caching
      CONDA_PKGS_DIRS: ${{ runner.temp }}/conda_pkgs
    steps:
      - uses: actions/checkout@v4

      - name: Add conda to PATH
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Install mamba
        run: |
          # install mamba into the base env
          conda install -n base -c conda-forge mamba -y

      - name: Create cache directory
        run: |
          mkdir -p $CONDA_PKGS_DIRS

      - name: Install dependencies with mamba
        run: |
          mamba env update --file environment.yml --name base
